# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: process.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'process.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprocess.proto\x12\x07process\"9\n\x13StartProcessRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"H\n\x0fProcessResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x1f\n\nLogRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"W\n\nLogMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\x0c\x12\x12\n\nprocess_id\x18\x04 \x01(\t2\x96\x01\n\x0eProcessService\x12H\n\x0cStartProcess\x12\x1c.process.StartProcessRequest\x1a\x18.process.ProcessResponse\"\x00\x12:\n\nStreamLogs\x12\x13.process.LogRequest\x1a\x13.process.LogMessage\"\x00\x30\x01\x42\x0bZ\t./processb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./process'
  _globals['_STARTPROCESSREQUEST']._serialized_start=26
  _globals['_STARTPROCESSREQUEST']._serialized_end=83
  _globals['_PROCESSRESPONSE']._serialized_start=85
  _globals['_PROCESSRESPONSE']._serialized_end=157
  _globals['_LOGREQUEST']._serialized_start=159
  _globals['_LOGREQUEST']._serialized_end=190
  _globals['_LOGMESSAGE']._serialized_start=192
  _globals['_LOGMESSAGE']._serialized_end=279
  _globals['_PROCESSSERVICE']._serialized_start=282
  _globals['_PROCESSSERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
